from fastapi import APIRouter, HTTPException, Depends, Query
from typing import Dict, Any, Optional
import json
from datetime import datetime
from app.models import User
from app.auth import get_current_user
from app.database import get_db_connection

router = APIRouter(prefix="/api/reports", tags=["Supervisory Assessment Reports & Dossiers"])

@router.get("/assessment-dossier", response_model=Dict[str, Any])
def generate_assessment_dossier(
    entity_id: Optional[str] = Query(None),
    current_user: User = Depends(get_current_user)
):
    """
    Generates a formal NCIIPC supervisory assessment report containing executive summary,
    resilience index breakdown, high-priority findings with counterfactuals, and examiner review status.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    if entity_id:
        cursor.execute("SELECT * FROM entities WHERE id = ?", (entity_id,))
        entities = [dict(cursor.fetchone())]
        cursor.execute("SELECT * FROM findings WHERE entity_id = ? ORDER BY priority_score DESC", (entity_id,))
        findings_rows = cursor.fetchall()
    else:
        cursor.execute("SELECT * FROM entities ORDER BY resilience_score ASC")
        entities = [dict(r) for r in cursor.fetchall()]
        cursor.execute("SELECT * FROM findings ORDER BY priority_score DESC")
        findings_rows = cursor.fetchall()
        
    conn.close()
    
    findings = []
    for r in findings_rows:
        findings.append({
            "id": r["id"],
            "entity_id": r["entity_id"],
            "entity_name": r["entity_name"],
            "rule_id": r["rule_id"],
            "title": r["title"],
            "category": r["category"],
            "severity": r["severity"],
            "priority_score": r["priority_score"],
            "what": r["what"],
            "why": r["why"],
            "expected_workflow": json.loads(r["expected_workflow_json"] or "[]"),
            "observed_workflow": json.loads(r["observed_workflow_json"] or "[]"),
            "supporting_evidence": json.loads(r["supporting_evidence_json"] or "{}"),
            "counterfactual_explanation": r["counterfactual_explanation"],
            "recommended_action": r["recommended_action"],
            "review_status": r["review_status"],
            "examiner_notes": r["examiner_notes"],
            "reviewed_by": r["reviewed_by"]
        })
        
    # Generate Markdown Report format
    md_lines = [
        f"# NCIIPC SUPERVISORY SOC ASSESSMENT DOSSIER",
        f"**Classification**: STRICTLY CONFIDENTIAL — SUPERVISORY USE ONLY",
        f"**Generated By**: {current_user.full_name} ({current_user.organization}) — Badge: {current_user.badge_number}",
        f"**Date Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "## 1. Executive Summary",
        f"This document presents the supervisory audit findings evaluated across {len(entities)} Critical Sector Entities (CSEs). A total of {len(findings)} operational anomalies, negative-space signals, and execution gaps were prioritized for manual verification.",
        "",
        "## 2. Entity Resilience Scoreboard",
        "| Entity Code | Entity Name | Sector | Criticality Tier | Resilience Score | Findings |",
        "|---|---|---|---|---|---|"
    ]
    
    for e in entities:
        md_lines.append(f"| {e['code']} | {e['name']} | {e['sector']} | {e['criticality_tier']} | **{e['resilience_score']} / 100** | {e['total_findings']} |")
        
    md_lines.append("")
    md_lines.append("## 3. High-Priority Supervisory Findings")
    
    for idx, f in enumerate(findings[:10], 1):
        md_lines.append(f"### {idx}. [{f['severity'].upper()}] {f['title']} (Priority: {f['priority_score']}/100)")
        md_lines.append(f"- **Entity**: {f['entity_name']} ({f['entity_id']})")
        md_lines.append(f"- **Category**: {f['category']} | **Rule ID**: `{f['rule_id']}`")
        md_lines.append(f"- **Status**: `{f['review_status']}`")
        md_lines.append(f"- **WHAT**: {f['what']}")
        md_lines.append(f"- **WHY**: {f['why']}")
        md_lines.append(f"- **Counterfactual**: *{f['counterfactual_explanation']}*")
        md_lines.append(f"- **Recommended Supervisory Action**: {f['recommended_action']}")
        if f['examiner_notes']:
            md_lines.append(f"- **Examiner Annotation**: \"{f['examiner_notes']}\" (by {f['reviewed_by']})")
        md_lines.append("")
        
    return {
        "report_id": f"DOSSIER-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
        "generated_at": datetime.utcnow().isoformat(),
        "generated_by": current_user.full_name,
        "badge_number": current_user.badge_number,
        "entities": entities,
        "total_findings": len(findings),
        "high_priority_findings": findings,
        "markdown_content": "\n".join(md_lines)
    }
