import React from 'react';
import { AlertOctagon, HelpCircle, ShieldAlert, Sparkles, CheckCircle2 } from 'lucide-react';
import { NegativeSpaceMatrixItem, Finding } from '../types';
import { NegativeSpaceHeatmap } from '../components/NegativeSpaceHeatmap';

interface NegativeSpaceViewProps {
  matrix: NegativeSpaceMatrixItem[];
  findings: Finding[];
  onSelectFinding: (finding: Finding) => void;
}

export const NegativeSpaceView: React.FC<NegativeSpaceViewProps> = ({
  matrix,
  findings,
  onSelectFinding,
}) => {
  const negativeFindings = findings.filter(
    (f) => f.category === 'Negative Space' || f.category === 'Asset Visibility'
  );

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-red-400 font-mono text-xs uppercase tracking-widest font-bold">
          <AlertOctagon className="h-4 w-4" />
          <span>Negative-Space Analysis & Operational Blindspots</span>
        </div>
        <h1 className="text-2xl font-bold text-slate-100 tracking-tight mt-1">
          Missing Expected Supervisory Workflow Evidence
        </h1>
        <p className="text-xs text-slate-400 mt-1 max-w-3xl leading-relaxed">
          In cybersecurity supervision, what is <strong>missing</strong> is often as critical as what is present. SAT-SA's Negative-Space Engine correlates observed logs against mandatory regulatory workflows to flag missing escalations, missing forensic memory captures, unmanaged shadow assets, and unverified closures.
        </p>
      </div>

      {/* Heatmap Matrix */}
      <NegativeSpaceHeatmap data={matrix} />

      {/* Negative Space Concept Explanation Box */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-2">
          <div className="text-xs font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="h-4 w-4" />
            <span>1. Missing Escalations</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            When Tier-1 analysts encounter Critical SCADA telemetry spoofing or malware persistence but close tickets locally without invoking Tier-2 Incident Command.
          </p>
        </div>

        <div className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-2">
          <div className="text-xs font-bold text-purple-400 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="h-4 w-4" />
            <span>2. Missing Forensic Hashes</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Intrusion cases marked as "Mitigated" or "Resolved" where investigation records fail to capture immutable SHA-256 process hashes, network PCAP, or memory dumps.
          </p>
        </div>

        <div className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-2">
          <div className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="h-4 w-4" />
            <span>3. Unmanaged Shadow Assets</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Security alerts generated by active network nodes and gateways that are entirely absent from the CSE's declared asset inventory baseline.
          </p>
        </div>
      </div>

      {/* Negative Space Findings Feed */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider flex items-center gap-2">
            <ShieldAlert className="h-4 w-4 text-red-400" />
            <span>Identified Negative Space Findings ({negativeFindings.length})</span>
          </h2>
        </div>

        <div className="space-y-3">
          {negativeFindings.map((finding) => (
            <div
              key={finding.id}
              onClick={() => onSelectFinding(finding)}
              className="glass-panel p-5 rounded-2xl border border-red-500/20 hover:border-red-500/40 hover:bg-slate-900/60 transition-all cursor-pointer group flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div className="space-y-1.5 flex-1">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold font-mono bg-red-950/80 text-red-400 border border-red-500/40">
                    NEGATIVE SPACE
                  </span>
                  <span className="text-xs font-mono text-cyan-400 font-semibold">
                    {finding.rule_id}
                  </span>
                  <span className="text-xs text-slate-400">
                    • {finding.entity_name}
                  </span>
                </div>

                <h3 className="text-sm font-bold text-slate-100 group-hover:text-cyan-300 transition-colors">
                  {finding.title}
                </h3>

                <p className="text-xs text-slate-400 leading-relaxed line-clamp-2">
                  {finding.what}
                </p>

                <div className="text-xs italic text-purple-300 font-medium">
                  "{finding.counterfactual_explanation}"
                </div>
              </div>

              <div className="shrink-0 text-right">
                <div className="text-[10px] uppercase font-mono text-slate-400">Priority</div>
                <div className="text-xl font-extrabold text-cyan-300 font-mono">
                  {finding.priority_score}<span className="text-xs text-slate-500">/100</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
